name: artificial_intelligence
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  http: ^1.2.1
  crypto: ^3.0.3
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  pin_code_text_field: ^1.8.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  internet_connection_checker: ^2.0.0
  flutter_native_splash: ^2.3.13
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  path_provider: ^2.0.15
  rename: ^3.0.2
  dio: ^5.3.2
  intl: ^0.19.0
  webview_flutter: ^3.0.4
  flutter_media_downloader: ^1.0.6
  url_launcher: ^6.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash.png
    - assets/images/login_bg.jfif.jpg
    - assets/fonts/roboto//
    - assets/fonts/typogarphy/
    - assets/fonts/Lintel-Reg-Ital/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Typography
      fonts:
        - asset: assets/fonts/typogarphy/Typography Times Regular.ttf
    - family: Lintel
      fonts:
        - asset: assets/fonts/Lintel-Reg-Ital/Lintel-Italic.ttf
        - asset: assets/fonts/Lintel-Reg-Ital/Lintel-Regular.ttf
