name: artificial_intelligence
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  http: ^1.2.1
  crypto: ^3.0.3
  get: ^4.6.6
  flutter_localizations:
      sdk: flutter
  shared_preferences: ^2.2.3
  pin_code_text_field: ^1.8.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
    # flutter_html: ^3.0.0-beta.2
  internet_connection_checker: ^2.0.0
#  file_picker: ^8.0.6
#  url_launcher: ^6.3.0
#  sentry_flutter: ^8.5.0
  flutter_native_splash: ^2.3.13



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # example:
  fonts:
    - family: Typography Times
      fonts:
        - asset: assets/fonts/typogarphy/Typography Times Bold.ttf
        - asset: assets/fonts/typogarphy/Typography Times Bold Italic.ttf
        - asset: assets/fonts/typogarphy/Typography Times Italic.ttf
        - asset: assets/fonts/typogarphy/Typography Times Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
